AWSTemplateFormatVersion: 2010-09-09
Description: Serves JIRA Standalone with DB running on separate machine.
Resources:
  Database:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: c4.xlarge
      SubnetId:
        Ref: Subnet
      SecurityGroupIds:
        - Ref: SshSecurityGroup
        - Ref: MySqlSecurityGroup
      KeyName:
        Ref: KeyName
      ImageId: !Ref Ami
      Tags:
        -
          Key: jpt-database
          Value: true
      IamInstanceProfile: !Ref InstanceProfile
      BlockDeviceMappings:
        -
          DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 100
            VolumeType: gp2
  MySqlSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Ref: VPC
      GroupDescription: Enables MySql access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0